stages:
  - prepare
  - deploy

prepare_db:
  stage: prepare
  image: bitnami/git
  script:
    - > # choosing the Registry for all images
     if [ "${RECLADA_REGISTRY}" == "false" ]; then
       echo "REPO_URL=588200329560.dkr.ecr.eu-west-1.amazonaws.com" >> prepare.env
     else
       echo "REPO_URL=registry.reclada.com/developers/${CI_PROJECT_TITLE}" >> prepare.env
     fi
    - echo ENV=$ENV >> prepare.env
    - echo NAMESPACE = reclada-$ENV >> prepare.env
    - echo DBNAME = "${ENV}_reclada_k8s" >> prepare.env 
    - echo LAMBDA_NAME = "s3_get_presigned_url_${ENV}" >> prepare.env
    - echo LAMBDA_REGION = "eu-west-1" >> prepare.env
  artifacts:
    reports:
      dotenv: prepare.env
  rules:
    - when: always 
  tags:
    - k8s-devops

deploy_db:
  stage: deploy
  image: $REPO_URL/db-installer:0.1
  script:
    - echo "Cloning configurations from all repos"
    
    - cd $CI_PROJECT_DIR/
    - mkdir cloned_repos && cd cloned_repos/
    - git clone -b $DB_BRANCH https://gitlab-deploy-token:${DEPLOY_TOKEN}@gitlab.reclada.com/developers/db.git
   # - git clone -b $WEBUI_BRANCH https://gitlab-deploy-token:${DEPLOY_TOKEN}@gitlab.reclada.com/developers/webui.git
    - git clone -b $RUNTIME_BRANCH https://gitlab-deploy-token:${DEPLOY_TOKEN}@gitlab.reclada.com/developers/reclada-runtime.git
    - git clone -b $SCINLP_BRANCH https://gitlab-deploy-token:${DEPLOY_TOKEN}@gitlab.reclada.com/developers/scinlp.git
    - git clone https://gitlab-deploy-token:${DEPLOY_TOKEN}@gitlab.reclada.com/developers/configurations.git
    - git clone https://gitlab-deploy-token:${DEPLOY_TOKEN}@gitlab.reclada.com/developers/components.git
    
    - echo "Create database for the environment"
      # here can be changes for db update config
      
    - cp $CI_PROJECT_DIR/cloned_repos/reclada-runtime/configuration_default.json $CI_PROJECT_DIR/cloned_repos/reclada-runtime/configuration.json
    - sed -i "s|\"LAMBDA_NAME\":.*|\"LAMBDA_NAME\":\ \"$LAMBDA_NAME\",|g" $CI_PROJECT_DIR/cloned_repos/reclada-runtime/configuration.json
    - sed -i "s|\"LAMBDA_REGION\":.*|\"LAMBDA_REGION\":\ \"$LAMBDA_REGION\",|g" $CI_PROJECT_DIR/cloned_repos/reclada-runtime/configuration.json 
    - sed -i "s|\"ENVIRONMENT_NAME\" :.*|\"ENVIRONMENT_NAME\" :\ \"K8S\"|g" $CI_PROJECT_DIR/cloned_repos/reclada-runtime/configuration.json

    - echo "Runtime configuration:"
    - cat $CI_PROJECT_DIR/cloned_repos/reclada-runtime/configuration.json

    - echo "DB configuration:"
    - cat $CI_PROJECT_DIR/cloned_repos/configurations/$ENV.json
    
    - echo "Run the installation script"
    - cd $CI_PROJECT_DIR/cloned_repos/components/
    - python installer.py $ENV    
  needs:
    - job: prepare_db
      artifacts: true
  tags:
    - k8s-devops
  rules:
    - when: always
