stages:
  - prepare
  - build
  - test
  - deploy
  - autotest
  - push-to-github

prepare_db:
  stage: prepare
  image: bitnami/git
  script:
    - echo $CI_OPEN_MERGE_REQUESTS
    - echo "DEV_RDS=dev-reclada-k8s.c9lpgtggzz0d.eu-west-1.rds.amazonaws.com" >> prepare.env
    - echo "TEST_RDS=test-reclada-k8s.c9lpgtggzz0d.eu-west-1.rds.amazonaws.com" >> prepare.env
    - echo "PROD_RDS=prod-reclada-k8s.c9lpgtggzz0d.eu-west-1.rds.amazonaws.com" >> prepare.env
    # - echo LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`) >> prepare.env
    - echo ENV=$(echo $CI_COMMIT_REF_NAME | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]') >> prepare.env
    - export ENV=$(echo $CI_COMMIT_REF_NAME | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]') >> prepare.env
    - echo DBNAME = "${ENV}_reclada_k8s" >> prepare.env 
    - echo LAMBDA_NAME = "s3_get_presigned_url_${ENV}" >> prepare.env
    #debug
    - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  artifacts:
    reports:
      dotenv: prepare.env
  rules:
    - if: $CI_COMMIT_REF_NAME !~ /^dynamic/ && $CI_MERGE_REQUEST_ID =~ /^./ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: always
    - if: $CI_COMMIT_REF_NAME !~ /^dynamic/ && $CI_MERGE_REQUEST_ID =~ /^./ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "test"
      when: always
    - if: $CI_COMMIT_REF_NAME !~ /^dynamic/ 
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /^dynamic/
      when: always
    - if: $CI_COMMIT_REF_NAME == "main"
      when: always
    - if: $CI_COMMIT_REF_NAME == "test"
      when: never
  tags:
    - k8s-devops

deploy-dynamic-env:
  stage: deploy
  image: 588200329560.dkr.ecr.eu-west-1.amazonaws.com/db-installer:0.1
  script:
    - echo "Create database for dynamic env"

    - cp $CI_PROJECT_DIR/update/update_config_template.json $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"branch_db\" :.*|\"branch_db\" :\ \"$CI_COMMIT_REF_NAME\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"server\" :.*|\"server\" :\ \"$DEV_RDS\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"db\" :.*|\"db\" :\ \"$DBNAME\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"db_user\" :.*|\"db_user\" :\ \"reclada\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"db_URI\" :.*|\"db_URI\" :\ \"postgresql://reclada:${PGPASSWORD}@${DEV_RDS}:5432/${DBNAME}\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"LAMBDA_NAME\" :.*|\"LAMBDA_NAME\" :\ \"$LAMBDA_NAME\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"ENVIRONMENT_NAME\" :.*|\"ENVIRONMENT_NAME\" :\ \"K8S\",|g" $CI_PROJECT_DIR/update/update_config.json

    - cat $CI_PROJECT_DIR/update/update_config.json
    - python --version
    - psql -V
    - cd $CI_PROJECT_DIR/update && psql -t -P pager=off -c "select max(ver) from dev.ver;" $(python -c "from update_db import db_URI;print(db_URI)") && python $CI_PROJECT_DIR/update/update_db.py || python $CI_PROJECT_DIR/update/install_db.py
  needs:
    - job: prepare_db
      artifacts: true
  tags:
    - k8s-devops
  rules:
  - if: $CI_MERGE_REQUEST_ID =~ /^./ 
    when: never
  - if: $CI_COMMIT_REF_NAME !~ /^dynamic/ 
    when: never
  - if: $CI_COMMIT_REF_NAME =~ /^dynamic/
    when: always
  - if: $CI_COMMIT_REF_NAME == "main"
    when: never
  - if: $CI_COMMIT_REF_NAME == "test"
    when: never

deploy-autotest-env:
  stage: deploy
  image: 588200329560.dkr.ecr.eu-west-1.amazonaws.com/db-installer:0.1
  script:
    - echo "Run update database in autotest env"
    
    - cp $CI_PROJECT_DIR/update/update_config_template.json $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"branch_db\" :.*|\"branch_db\" :\ \"$CI_COMMIT_REF_NAME\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"server\" :.*|\"server\" :\ \"$TEST_RDS\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"db\" :.*|\"db\" :\ \"autotest_reclada_k8s\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"db_user\" :.*|\"db_user\" :\ \"reclada\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"db_URI\" :.*|\"db_URI\" :\ \"postgresql://reclada:${PGPASSWORD}@${TEST_RDS}:5432/autotest_reclada_k8s\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"LAMBDA_NAME\" :.*|\"LAMBDA_NAME\" :\ \"s3_get_presigned_url_autotest\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"ENVIRONMENT_NAME\" :.*|\"ENVIRONMENT_NAME\" :\ \"K8S\",|g" $CI_PROJECT_DIR/update/update_config.json

    - cat $CI_PROJECT_DIR/update/update_config.json
    - python --version
    - psql -V
    - cd $CI_PROJECT_DIR/update && psql -t -P pager=off -c "select max(ver) from dev.ver;" $(python -c "from update_db import db_URI;print(db_URI)") && python $CI_PROJECT_DIR/update/update_db.py || python $CI_PROJECT_DIR/update/install_db.py
  needs:
    - job: prepare_db
      artifacts: true
  tags:
      - k8s-devops
  rules:
    - if: $CI_MERGE_REQUEST_ID =~ /^./ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "test"
      when: always
    - if: $CI_COMMIT_REF_NAME !~ /^dynamic/ 
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /^dynamic/
      when: never
    - if: $CI_COMMIT_REF_NAME == "main"
      when: never
    - if: $CI_COMMIT_REF_NAME == "test"
      when: never


test-autotest-env:
  stage: autotest
  # image: ???
  script:
    - echo "Run some tests for autotest env"
    - echo $CI_COMMIT_REF_NAME
  needs:
    - job: deploy-autotest-env
  tags:
      - k8s-devops
  rules:
    - if: $CI_MERGE_REQUEST_ID =~ /^./ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "test"
      when: always
    - if: $CI_COMMIT_REF_NAME !~ /^dynamic/ 
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /^dynamic/
      when: never
    - if: $CI_COMMIT_REF_NAME == "main"
      when: never
    - if: $CI_COMMIT_REF_NAME == "test"
      when: never
    

deploy-prod-env:
  stage: deploy
  image: 588200329560.dkr.ecr.eu-west-1.amazonaws.com/db-installer:0.1
  script:
    - echo "Run update database in prod env"

    - cp $CI_PROJECT_DIR/update/update_config_template.json $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"branch_db\" :.*|\"branch_db\" :\ \"main\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"server\" :.*|\"server\" :\ \"$PROD_RDS\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"db\" :.*|\"db\" :\ \"prod_reclada_k8s\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"db_user\" :.*|\"db_user\" :\ \"reclada\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"db_URI\" :.*|\"db_URI\" :\ \"postgresql://reclada:${PGPASSWORD}@${PROD_RDS}:5432/prod_reclada_k8s\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"LAMBDA_NAME\" :.*|\"LAMBDA_NAME\" :\ \"s3_get_presigned_url_prod\",|g" $CI_PROJECT_DIR/update/update_config.json
    - sed -i "s|\"ENVIRONMENT_NAME\" :.*|\"ENVIRONMENT_NAME\" :\ \"K8S\",|g" $CI_PROJECT_DIR/update/update_config.json

    - cat $CI_PROJECT_DIR/update/update_config.json
    - python --version
    - psql -V
    - python $CI_PROJECT_DIR/update/update_db.py || python $CI_PROJECT_DIR/update/install_db.py
  # needs:
  #   - job: prepare_db
  #     artifacts: true
  tags:
      - k8s-devops
  rules:
    - if: $CI_MERGE_REQUEST_ID =~ /^./ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "test"
      when: never
    - if: $CI_MERGE_REQUEST_ID =~ /^./ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: never
    - if: $CI_COMMIT_REF_NAME !~ /^dynamic/ 
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /^dynamic/
      when: never
    - if: $CI_COMMIT_REF_NAME == "main"
      when: always
    - if: $CI_COMMIT_REF_NAME == "test"
      when: never

push-to-github:
  stage: push-to-github
  image: bitnami/git
  script:
    - echo "Run push to github"
    - ls -la
    - echo $CI_PROJECT_NAME
    - git remote set-url origin https://gitlab:${MY_GITHUB_TOKEN}@github.com/reclada/${CI_PROJECT_NAME}.git
    - rm -rf Gitlab_image/
    - rm -rf .gitlab-ci.yml
    - ls -la
    - git config --global user.email "Gitlab@reclada.com"
    - git config --global user.name "Gitlab runner"
    - git add .
    - git commit -am "${CI_COMMIT_MESSAGE}"
    - git push origin add/push-github  --force
  # needs:
  #   - job: prepare_db
  #     artifacts: true
  tags:
      - k8s-devops
  rules:
    - if: $CI_COMMIT_REF_NAME == "add/push-github"
      when: always
    - if: $CI_MERGE_REQUEST_ID =~ /^./ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "test"
      when: never
    - if: $CI_MERGE_REQUEST_ID =~ /^./ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: never
    - if: $CI_COMMIT_REF_NAME !~ /^dynamic/ 
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /^dynamic/
      when: never
    - if: $CI_COMMIT_REF_NAME == "test"
      when: never
